### PR TITLE
Plan. Model, Events, Listeners. In Manager retrievePlans. Console command

### PR DESCRIPTION
**Pull request by webcome**
Hi,
I've added Plan. Model, Events, Listeners. In Manager retrievePlans. Console command stripe:plan:update for update plans.
If you can see well you will merge.
Thanks.

### CODE REVIEW

**Comment by webcome** [comment]
Hi,

Travis CI show error in php:hhvm, I found the follow issue, can you review it?

        #composer/composer/issues/4976

https://github.com/composer/composer/issues/4976

Thanks you.

**Comment by Aerendir** [comment]
Hi @webcome , I'm happy to see you again :)

So, about the travi-ci error, I'll simply remove the hhvm test from the matrix, since it seems there is a problem on their own. So, if someone is using HVHVM, it should be aware of the problems and fix them on his own.

Another lst thing: can you add just a bit of documentation [here](https://github.com/Aerendir/stripe-bundle/blob/master/Resources/docs/Backend-Integration.md)? Just some lines to explain the basic of the use of Subscriptions and Plans and use of the `stripe:update:plans` command.

**Comment by Aerendir** [comment]
@webcome , I've just fixed all unit tests. Please, pull to keep in synch with the `master` branch...

**Comment by webcome** [comment]
Hi @Aerendir, I added a bit of documentation and synch with master and change requirement of phpunit to 5.* for passing the tests. I can see you change hhvm to nightly but the tests are not passing there. Can you review it?

**Comment by Aerendir** [comment]
@webcome , yes, I dropped the tests for HHVM as is is currently incompatible with PHP 7 (from a link you posted above). So, in the meantime, we drop the support waiting for a support on their part.

The tests currently fails on PHP 7.2 (the `nightly`)  due to an error in the handling of the forms by Symfony, so we have no power of fixing them currently. I've opened an issue on the Symfony's issue tracker to get some support about (https://github.com/symfony/symfony/issues/21511#issuecomment-277191234). Is a bug already reported and "to-be-fixed".

So, anyway I'll go to merge your PR as you did a very great job! Many many thanks! :)

**Comment by Aerendir** [comment]
Just one last thing: if you see the checks of SensioInsights, you'll see a lot of issue with the update plans command. Maybe you can fix them in another PR...

**Pull request merged**
