### PR TITLE
Add Subscriptions. Model, Event, Listener, Tests...

### PR DESCRIPTION
**Pull request by webcome**
Hello, 
I need to use subscriptions on stripe and create the model, event, listener.
If you find it useful you can pull.

### CODE REVIEW

**Comment by Aerendir** [comment]
Thank you @webcome . I'll give it a try asap!

**Comment by webcome** [comment]
Hi, 
It's allowed to cancel a subscriptions.
Bye.

**Comment by Aerendir** [comment]
Hi @webcome , again thank you! Currently I'm developing FeaturesBundle (https://github.com/Aerendir/bundle-features) and so I haven't the time to check the PR. But your PR will be the first thing I'll check once I'll start again working on this bundle (is the next step after the FeaturesBundle). Again, thank you for the contribution!

**Comment by Aerendir** [comment]
Hi @webcome , I've just merged your PR... Thankyou very much for the contribution: it is greatly appreciated!

**Pull request merged**
